name: Upload module files to Azure Blob Storage

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Very Simple Hello World
        uses: phwes/simple_hello_world@v1
